### ISSUE TITLE
connectivity app getting disconnected

### ISSUE THREAD

**Issue by bbest** [marinebon/sdg14-shiny#1]
Hi @stephgad,

From the larval connectivity Shiny app http://mbon.marine.usf.edu:3838/conn/ and after drawing a polygon using with default parameters, am getting the message "Disconnected from the server. Reload". 

![image](https://user-images.githubusercontent.com/2837257/30242842-e2302c7c-9552-11e7-89f9-fd487c1e45c8.png)

This seems to be related to the `FromPatchID` not being found in the `*_results/connectivity.csv` file as defined by [conn/server.R#L33-L40](https://github.com/marinebon/sdg14-shiny/blob/master/conn/server.R#L33-L40).

Did you happen to update these files on the mbon.marine.usf.edu server per the scant info I gave you using CyberDuck?

Thanks, Ben

```
ben@mbon:/mbon/shiny-log$ cat conn-shiny-20170909-183234-34007.log 
Loading tidyverse: ggplot2
Loading tidyverse: tibble
Loading tidyverse: tidyr
Loading tidyverse: readr
Loading tidyverse: purrr
Loading tidyverse: dplyr
Conflicts with tidy packages ---------------------------------------------------
filter(): dplyr, stats
lag():    dplyr, stats
Linking to GEOS 3.5.1, GDAL 2.1.3, proj.4 4.8.0
Loading required package: sp
rgdal: version: 1.2-7, (SVN revision 660)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 2.1.3, released 2017/20/01
 Path to GDAL shared files: /usr/local/share/gdal
 Loaded PROJ.4 runtime: Rel. 4.8.0, 6 March 2012, [PJ_VERSION: 480]
 Path to PROJ.4 shared files: (autodetected)
 Linking to sp version: 1.2-4 

Attaching package: 'raster'

The following object is masked from 'package:dplyr':

    select

The following object is masked from 'package:tidyr':

    extract


Attaching package: 'geojsonio'

The following object is masked from 'package:shiny':

    validate

The following object is masked from 'package:base':

    pretty


Listening on http://127.0.0.1:34007
Warning in .local(x, y, ...) :
  Transforming SpatialPolygons to the CRS of the Raster
Warning: Error in resolve_vars: unknown variable to group by : FromPatchID
Stack trace (innermost first):
    79: <Anonymous>
    78: stop
    77: resolve_vars
    76: group_by_prepare
    75: group_by_.data.frame
    74: group_by_
    73: group_by
    72: function_list[[i]]
    71: freduce
    70: _fseq
    69: eval
    68: eval
    67: withVisible
    66: %>%
    65: observeEventHandler [/srv/shiny-server/conn/server.R#82]
     1: runApp
```

**Comment by stephgad** [comment]
Hi @bbest, 
I haven't updated anything on the mbon.marine.usf.edu server. 
Since the last time we met, I've just copied the files from my P and H drives to an external hard drive. 
Steph

**Comment by bbest** [comment]
Hi @stephgad,

Sorry about the lag fixing this. Something was wrong / outdated with the connectivity.csv files on the server. I uploaded them again with CyberDuck and all seems to be working again.
